from datetime import datetime, timedelta, timezone

from sqlalchemy.orm import Session

from app.models import (
    Application,
    ApplicationStatus,
    Bookmark,
    Category,
    Notification,
    NotificationType,
    Opportunity,
    OpportunityStatus,
    Organization,
    Role,
    Setting,
    User,
)
from app.security import hash_password
from app.utils import slugify


def _days(days: int) -> datetime:
    moment = datetime.now(timezone.utc) + timedelta(days=days)
    return moment.replace(hour=20, minute=0, second=0, microsecond=0)


def seed_if_empty(db: Session) -> None:
    if db.query(User).count() > 0:
        return

    categories = [
        ("Scholarships", "scholarships", "Funding for study, research, and living costs.", "GraduationCap", "#0C6B58"),
        ("Jobs", "jobs", "Full-time and part-time roles with local and international employers.", "Briefcase", "#1D4ED8"),
        ("Internships", "internships", "Short placements to build experience while you study.", "Building2", "#0F766E"),
        ("Courses", "courses", "Structured learning, from short courses to full programs.", "BookOpen", "#7C3AED"),
        ("Training", "training", "Practical workshops that build job-ready skills.", "Presentation", "#B45309"),
        ("Hackathons", "hackathons", "Time-boxed builds for students who like to ship.", "Code2", "#BE123C"),
        ("Competitions", "competitions", "Challenges, prizes, and a public result.", "Trophy", "#C2410C"),
        ("Fellowships", "fellowships", "Funded periods of research, leadership, or practice.", "Award", "#0369A1"),
        ("Volunteering", "volunteering", "Ways to contribute skills to community work.", "HeartHandshake", "#15803D"),
        ("Events", "events", "Fairs, forums, and gatherings worth showing up for.", "CalendarDays", "#4338CA"),
    ]
    category_map: dict[str, Category] = {}
    for name, slug, description, icon, color in categories:
        row = Category(name=name, slug=slug, description=description, icon=icon, color=color)
        db.add(row)
        category_map[slug] = row

    organizations = [
        ("University of Hargeisa", "university-of-hargeisa", "The main public university in Hargeisa, with faculties across ICT, health, education, and business.", "https://uoh-edu.net", "info@uoh-edu.net", "+252 63 000 000", "Hargeisa", True),
        ("Gollis University", "gollis-university", "A private university in Hargeisa offering computing, business, and health programs.", "https://gollisuniversity.org", "info@gollisuniversity.org", None, "Hargeisa", True),
        ("Amoud University", "amoud-university", "A university in Borama known for medicine, engineering, and research training.", "https://amouduniversity.org", "info@amouduniversity.org", None, "Borama", True),
        ("Hargeisa Tech Hub", "hargeisa-tech-hub", "A community workspace for developers, designers, and early-stage teams in Hargeisa.", "https://hargeisatechhub.example", "hello@hargeisatechhub.example", None, "Hargeisa", True),
        ("Telesom", "telesom", "A telecommunications company hiring engineers, analysts, and customer specialists.", "https://www.telesom.com", "careers@telesom.com", None, "Hargeisa", True),
        ("Dahabshiil", "dahabshiil", "A financial services group with graduate pathways in finance and operations.", "https://www.dahabshiil.com", "careers@dahabshiil.com", None, "Hargeisa", True),
        ("Shaqodoon", "shaqodoon", "A youth employment organization running work-readiness and placement programs.", "https://shaqodoon.org", "info@shaqodoon.org", None, "Hargeisa", True),
        ("SPARK", "spark", "An international organization supporting entrepreneurship and higher education.", "https://spark.ngo", "info@spark.ngo", None, "Hargeisa", True),
        ("Ministry of Education", "ministry-of-education", "Public education programs, teaching pathways, and national events.", "https://moe.govsomaliland.org", "info@moe.govsomaliland.org", None, "Hargeisa", True),
        ("UNDP Somalia", "undp-somalia", "Development programs that include youth innovation and graduate fellowships.", "https://www.undp.org", "registry.so@undp.org", None, "Hargeisa", True),
    ]
    org_map: dict[str, Organization] = {}
    for name, slug, description, website, email, phone, location, verified in organizations:
        row = Organization(
            name=name,
            slug=slug,
            description=description,
            website=website,
            email=email,
            phone=phone,
            location=location,
            verified=verified,
        )
        db.add(row)
        org_map[slug] = row

    db.flush()

    bachelor = ["Bachelor", "Diploma"]
    any_level = ["High School", "Diploma", "Bachelor", "Master"]
    graduate = ["Bachelor", "Master"]

    opportunities = [
        {
            "title": "Telesom Software Engineering Internship",
            "org": "telesom",
            "category": "internships",
            "type": "INTERNSHIP",
            "location": "Hargeisa",
            "country": "Somaliland",
            "remote": False,
            "days": 2,
            "views": 860,
            "featured": True,
            "skills": ["Python", "TypeScript", "React"],
            "tags": ["Software Engineering", "Mobile", "Paid"],
            "levels": bachelor,
            "short": "A 12-week engineering placement building products used by customers across Somaliland.",
            "description": "Telesom is hiring software engineering students who want production experience. Interns join a small product team, ship a scoped feature, and present it at the end of the placement.\n\nYou will work with engineers on web and internal tools, write tested code, and learn how a telecom product team reviews work.",
            "eligibility": "Open to bachelor students in Software Engineering, Computer Science, or a related field, based in Hargeisa.",
            "requirements": "Coursework in programming. A small project in Python, TypeScript, or React. Ability to join the Hargeisa office three days a week.",
            "benefits": "Mentor, transport stipend, and a reference letter if you complete the placement.",
            "url": "https://www.telesom.com",
        },
        {
            "title": "AI for Somaliland Hackathon",
            "org": "hargeisa-tech-hub",
            "category": "hackathons",
            "type": "HACKATHON",
            "location": "Hargeisa",
            "country": "Somaliland",
            "remote": False,
            "days": 1,
            "views": 1240,
            "featured": True,
            "skills": ["Python", "AI", "TypeScript"],
            "tags": ["Artificial Intelligence", "Software Engineering", "Weekend"],
            "levels": any_level,
            "short": "A 36-hour build weekend for students using AI on local problems.",
            "description": "Teams of two to four design a prototype that uses artificial intelligence for education, health, or public services in Somaliland. Mentors from Hargeisa Tech Hub staff the room.\n\nSoftware engineering students are especially welcome, including first-time hackers with a working project idea.",
            "eligibility": "Students and recent graduates in Hargeisa. Teams need at least one person who can code.",
            "requirements": "Bring a laptop. A short idea in artificial intelligence, data, or software engineering helps, but you can join a team on the day.",
            "benefits": "Meals, mentorship, and prizes for the top three teams.",
            "url": "https://hargeisatechhub.example/hackathon",
        },
        {
            "title": "Undergraduate Scholarship in Artificial Intelligence",
            "org": "university-of-hargeisa",
            "category": "scholarships",
            "type": "SCHOLARSHIP",
            "location": "Hargeisa",
            "country": "Somaliland",
            "remote": False,
            "days": 18,
            "views": 2104,
            "featured": True,
            "skills": ["AI", "Python", "Research"],
            "tags": ["Artificial Intelligence", "Software Engineering", "Tuition"],
            "levels": bachelor,
            "short": "Tuition support for software engineering students focusing on artificial intelligence.",
            "description": "The University of Hargeisa scholarship covers a share of tuition for students who want to go deeper into artificial intelligence. Recipients join a study group and complete a small research note.\n\nThe award is aimed at software engineering and computer science students with a clear academic record.",
            "eligibility": "Current bachelor students at a recognized university in Somaliland, with a focus on software engineering or computing.",
            "requirements": "Transcript, a one-page statement about artificial intelligence, and one faculty reference.",
            "benefits": "Partial tuition, a faculty mentor, and a seat in the AI study circle.",
            "url": "https://uoh-edu.net",
        },
        {
            "title": "Junior Frontend Developer",
            "org": "hargeisa-tech-hub",
            "category": "jobs",
            "type": "JOB",
            "location": "Hargeisa",
            "country": "Somaliland",
            "remote": False,
            "days": 12,
            "views": 980,
            "featured": True,
            "skills": ["React", "TypeScript"],
            "tags": ["Software Engineering", "Frontend"],
            "levels": graduate,
            "short": "A junior role building the hub's member portal and event tools.",
            "description": "Hargeisa Tech Hub needs a junior developer to improve the member portal. The work is React and TypeScript, with design support from the community team.\n\nThis is a good first job for a software engineering graduate who has shipped at least one project.",
            "eligibility": "Graduates and final-year students who can work from Hargeisa.",
            "requirements": "A portfolio with React. Comfort reading TypeScript. Clear written English or Somali for issue updates.",
            "benefits": "Salary, coworking membership, and learning budget.",
            "url": "https://hargeisatechhub.example/jobs",
        },
        {
            "title": "Remote AI Product Course",
            "org": "gollis-university",
            "category": "courses",
            "type": "COURSE",
            "location": "Remote",
            "country": "Somaliland",
            "remote": True,
            "days": 30,
            "views": 640,
            "featured": False,
            "skills": ["Python", "AI"],
            "tags": ["Artificial Intelligence", "Remote", "Course"],
            "levels": bachelor,
            "short": "An eight-week remote course on building small AI features with Python.",
            "description": "Gollis University is running a remote course for students who want practical artificial intelligence skills. Weekly labs use Python and end with a demo.\n\nSoftware engineering students can take it alongside their degree.",
            "eligibility": "Students who can commit five hours a week and have basic Python.",
            "requirements": "A laptop, stable internet, and an introductory programming course.",
            "benefits": "Certificate, project review, and office hours.",
            "url": "https://gollisuniversity.org",
        },
        {
            "title": "Dahabshiil Graduate Finance Internship",
            "org": "dahabshiil",
            "category": "internships",
            "type": "INTERNSHIP",
            "location": "Hargeisa",
            "country": "Somaliland",
            "remote": False,
            "days": 6,
            "views": 1500,
            "featured": True,
            "skills": ["Excel", "Finance", "Communication"],
            "tags": ["Finance", "Graduate"],
            "levels": graduate,
            "short": "A graduate internship in finance operations at Dahabshiil's Hargeisa office.",
            "description": "The internship rotates through reconciliation, reporting, and customer operations. Interns who do well are considered for analyst roles.\n\nYou will work with a supervisor and present one process improvement before the placement ends.",
            "eligibility": "Final-year or recent graduates in finance, accounting, business, or economics.",
            "requirements": "Spreadsheet skills, a transcript, and availability in Hargeisa.",
            "benefits": "Stipend and a formal review at week eight.",
            "url": "https://www.dahabshiil.com",
        },
        {
            "title": "Mastercard Foundation Scholars Pathway",
            "org": "university-of-hargeisa",
            "category": "scholarships",
            "type": "SCHOLARSHIP",
            "location": "International",
            "country": "International",
            "remote": False,
            "days": 40,
            "views": 3200,
            "featured": True,
            "skills": ["Leadership", "Research"],
            "tags": ["Scholarship", "Leadership"],
            "levels": ["Bachelor", "Master"],
            "short": "A guidance track for students preparing competitive international scholarship files.",
            "description": "University advisors help shortlisted students prepare applications for international scholarship programs, including document reviews and interview practice.\n\nThis is a preparation pathway, not a guaranteed award. The university nominates a limited number of candidates.",
            "eligibility": "High-performing students with financial need and a record of community contribution.",
            "requirements": "Transcript, need statement, and two references.",
            "benefits": "Application coaching and nomination support.",
            "url": "https://uoh-edu.net",
        },
        {
            "title": "UNDP Youth Innovation Fellowship",
            "org": "undp-somalia",
            "category": "fellowships",
            "type": "FELLOWSHIP",
            "location": "Hargeisa",
            "country": "Somaliland",
            "remote": False,
            "days": 25,
            "views": 1100,
            "featured": False,
            "skills": ["Research", "Communication", "Design"],
            "tags": ["Fellowship", "Innovation"],
            "levels": graduate,
            "short": "A six-month fellowship for young people prototyping civic and climate ideas.",
            "description": "Fellows receive a stipend, a mentor, and a cohort. The work happens in Hargeisa with two trips to meet partner teams.\n\nProjects should be realistic for local institutions, not slide decks alone.",
            "eligibility": "Young professionals and recent graduates in Somaliland.",
            "requirements": "A two-page proposal and a CV.",
            "benefits": "Stipend, mentorship, and a demo day.",
            "url": "https://www.undp.org",
        },
        {
            "title": "SPARK Entrepreneurship Training",
            "org": "spark",
            "category": "training",
            "type": "TRAINING",
            "location": "Hargeisa",
            "country": "Somaliland",
            "remote": False,
            "days": 9,
            "views": 540,
            "featured": False,
            "skills": ["Business", "Communication"],
            "tags": ["Entrepreneurship", "Training"],
            "levels": any_level,
            "short": "A three-week evening training on customer discovery and simple business models.",
            "description": "SPARK's trainers run practical sessions for students who want to test a small business or campus venture. You leave with a one-page model and a customer list.\n\nNo existing company is required.",
            "eligibility": "Students and young founders in Hargeisa.",
            "requirements": "Attendance at evening sessions and a short application form.",
            "benefits": "Trainer feedback and a certificate.",
            "url": "https://spark.ngo",
        },
        {
            "title": "National Student Debate",
            "org": "ministry-of-education",
            "category": "competitions",
            "type": "COMPETITION",
            "location": "Hargeisa",
            "country": "Somaliland",
            "remote": False,
            "days": 4,
            "views": 430,
            "featured": False,
            "skills": ["Communication", "Research"],
            "tags": ["Debate", "Public speaking"],
            "levels": any_level,
            "short": "A public debate competition for university teams, hosted in Hargeisa.",
            "description": "Teams of three debate a published motion on education and employment. Judges score argument, evidence, and teamwork.\n\nThe final is open to students from universities across Somaliland.",
            "eligibility": "Registered university students.",
            "requirements": "A team registration and a faculty sponsor.",
            "benefits": "Travel support for finalists outside Hargeisa and a public citation.",
            "url": "https://moe.govsomaliland.org",
        },
        {
            "title": "Weekend Teaching Volunteers",
            "org": "ministry-of-education",
            "category": "volunteering",
            "type": "VOLUNTEERING",
            "location": "Hargeisa",
            "country": "Somaliland",
            "remote": False,
            "days": 15,
            "views": 300,
            "featured": False,
            "skills": ["Education", "Communication"],
            "tags": ["Teaching", "Community"],
            "levels": any_level,
            "short": "Saturday tutoring for secondary students preparing for exams.",
            "description": "Volunteers support mathematics and English sessions in partner schools. A short orientation is required before the first Saturday.\n\nThis suits education students and anyone who can explain a topic clearly.",
            "eligibility": "Adults who can commit four Saturdays.",
            "requirements": "Orientation attendance and a simple background form.",
            "benefits": "Orientation, materials, and a service letter.",
            "url": "https://moe.govsomaliland.org",
        },
        {
            "title": "Hargeisa Career Fair",
            "org": "shaqodoon",
            "category": "events",
            "type": "EVENT",
            "location": "Hargeisa",
            "country": "Somaliland",
            "remote": False,
            "days": 8,
            "views": 1750,
            "featured": True,
            "skills": ["Communication"],
            "tags": ["Career", "Employers"],
            "levels": any_level,
            "short": "A one-day fair with employers, CV reviews, and short talks.",
            "description": "Shaqodoon brings employers and training providers into one hall. Students can book a 15-minute CV review and meet hiring teams from Hargeisa.\n\nArrive with printed copies and a one-minute introduction.",
            "eligibility": "Students, graduates, and job seekers.",
            "requirements": "Free registration. Bring a CV.",
            "benefits": "Employer meetings and CV feedback.",
            "url": "https://shaqodoon.org",
        },
        {
            "title": "Amoud Research Scholarship",
            "org": "amoud-university",
            "category": "scholarships",
            "type": "SCHOLARSHIP",
            "location": "Borama",
            "country": "Somaliland",
            "remote": False,
            "days": 3,
            "views": 410,
            "featured": False,
            "skills": ["Research", "Medicine"],
            "tags": ["Research", "Health"],
            "levels": ["Bachelor", "Master"],
            "short": "Support for a student research project in health or engineering at Amoud.",
            "description": "The scholarship funds field costs for a supervised research project. Preference goes to proposals that can be completed within one semester.\n\nApplicants need a faculty supervisor before they submit.",
            "eligibility": "Amoud students and visiting students with a local supervisor.",
            "requirements": "Proposal, budget, and supervisor letter.",
            "benefits": "Research costs and a presentation slot.",
            "url": "https://amouduniversity.org",
        },
        {
            "title": "Youth Employment Officer",
            "org": "shaqodoon",
            "category": "jobs",
            "type": "JOB",
            "location": "Hargeisa",
            "country": "Somaliland",
            "remote": False,
            "days": 21,
            "views": 720,
            "featured": False,
            "skills": ["Communication", "Excel"],
            "tags": ["NGO", "Youth"],
            "levels": graduate,
            "short": "Coordinate placements between employers and young job seekers.",
            "description": "The officer tracks applications, prepares candidates for interviews, and reports placement numbers. The role is based at the Hargeisa office with field visits.\n\nExperience as a student leader or volunteer is relevant.",
            "eligibility": "Graduates with strong communication skills.",
            "requirements": "CV and a short example of how you helped someone find work or training.",
            "benefits": "Salary and field transport.",
            "url": "https://shaqodoon.org",
        },
        {
            "title": "Remote React Developer",
            "org": "hargeisa-tech-hub",
            "category": "jobs",
            "type": "JOB",
            "location": "Remote",
            "country": "Somaliland",
            "remote": True,
            "days": 14,
            "views": 1330,
            "featured": False,
            "skills": ["React", "TypeScript", "Software Engineering"],
            "tags": ["Remote", "Software Engineering"],
            "levels": graduate,
            "short": "A remote contract to build dashboard screens for a local client project.",
            "description": "The hub is staffing a remote contract for a software engineering graduate who can work independently in React. The client is in Hargeisa; the work can be done from anywhere with reliable internet.\n\nYou will join standups twice a week.",
            "eligibility": "Developers who can overlap with Hargeisa working hours.",
            "requirements": "Two React samples and availability for a paid trial task.",
            "benefits": "Contract fee and a reference from the hub.",
            "url": "https://hargeisatechhub.example/react",
        },
        {
            "title": "Work Readiness Training",
            "org": "shaqodoon",
            "category": "training",
            "type": "TRAINING",
            "location": "Hargeisa",
            "country": "Somaliland",
            "remote": False,
            "days": 5,
            "views": 880,
            "featured": False,
            "skills": ["Communication"],
            "tags": ["CV", "Interviews"],
            "levels": any_level,
            "short": "Five sessions on CVs, interviews, and workplace habits.",
            "description": "A practical training for students entering internships and first jobs. Sessions include a live interview exercise and a CV rewrite.\n\nSeats are limited and filled in the order applications are completed.",
            "eligibility": "Students and recent graduates.",
            "requirements": "A current CV draft, even if it is rough.",
            "benefits": "Revised CV and interview practice.",
            "url": "https://shaqodoon.org",
        },
        {
            "title": "Africa Undergraduate AI Award",
            "org": "gollis-university",
            "category": "scholarships",
            "type": "SCHOLARSHIP",
            "location": "International",
            "country": "International",
            "remote": True,
            "days": 11,
            "views": 1600,
            "featured": False,
            "skills": ["AI", "Python"],
            "tags": ["Artificial Intelligence", "International"],
            "levels": bachelor,
            "short": "A remote award for undergraduates building an AI demo with a public write-up.",
            "description": "The award recognizes a small artificial intelligence project and a clear explanation of who it helps. Software engineering students in Somaliland are encouraged to apply.\n\nYou do not need a published paper. A working demo and a two-page note are enough.",
            "eligibility": "Undergraduate students in Africa.",
            "requirements": "Demo link, short write-up, and proof of enrollment.",
            "benefits": "Award payment and feedback from reviewers.",
            "url": "https://gollisuniversity.org",
        },
        {
            "title": "Community Health Drive",
            "org": "amoud-university",
            "category": "volunteering",
            "type": "VOLUNTEERING",
            "location": "Borama",
            "country": "Somaliland",
            "remote": False,
            "days": -4,
            "views": 220,
            "featured": False,
            "status": "EXPIRED",
            "skills": ["Medicine", "Communication"],
            "tags": ["Health"],
            "levels": ["Bachelor"],
            "short": "A completed outreach week for health students in Borama.",
            "description": "This volunteering week has ended. The listing stays visible to admins as an expired record and is hidden from the public catalogue.",
            "eligibility": "Health students.",
            "requirements": "Faculty approval.",
            "benefits": "Service hours.",
            "url": "https://amouduniversity.org",
        },
        {
            "title": "Product Design Fellowship",
            "org": "hargeisa-tech-hub",
            "category": "fellowships",
            "type": "FELLOWSHIP",
            "location": "Remote",
            "country": "Somaliland",
            "remote": True,
            "days": 16,
            "views": 510,
            "featured": False,
            "skills": ["Design", "Research"],
            "tags": ["Design", "Remote"],
            "levels": graduate,
            "short": "A remote fellowship for designers improving public-service forms and flows.",
            "description": "Fellows redesign one high-friction form used by students or clinics. The fellowship is remote, with a weekly critique.\n\nA portfolio of three flows is more useful than a long CV.",
            "eligibility": "Designers and computing students with interface work to show.",
            "requirements": "Portfolio and a short critique of a form you have used.",
            "benefits": "Stipend and a published case study.",
            "url": "https://hargeisatechhub.example/design",
        },
        {
            "title": "University Coding Challenge",
            "org": "university-of-hargeisa",
            "category": "competitions",
            "type": "COMPETITION",
            "location": "Hargeisa",
            "country": "Somaliland",
            "remote": False,
            "days": 0,
            "views": 990,
            "featured": True,
            "skills": ["Python", "Software Engineering"],
            "tags": ["Algorithms", "Software Engineering"],
            "levels": bachelor,
            "short": "A same-day programming challenge on campus. Closes tonight.",
            "description": "Students solve a set of Python problems under a time limit. The challenge is built for software engineering students and welcomes adjacent departments.\n\nRegistration closes at the end of today.",
            "eligibility": "Current university students with identification.",
            "requirements": "A laptop and basic Python.",
            "benefits": "Prizes and a ranking you can add to applications.",
            "url": "https://uoh-edu.net",
        },
        {
            "title": "Public Health Short Course",
            "org": "amoud-university",
            "category": "courses",
            "type": "COURSE",
            "location": "Borama",
            "country": "Somaliland",
            "remote": False,
            "days": 22,
            "views": 260,
            "featured": False,
            "skills": ["Medicine", "Research"],
            "tags": ["Health", "Course"],
            "levels": ["Bachelor", "Master"],
            "short": "A four-week short course on field methods for public health students.",
            "description": "The course covers survey design, ethics, and a supervised community visit. It is taught in Borama.\n\nComputing students are not the primary audience, but mixed teams are allowed for the data session.",
            "eligibility": "Health and related students.",
            "requirements": "Enrollment letter.",
            "benefits": "Certificate and faculty feedback.",
            "url": "https://amouduniversity.org",
        },
        {
            "title": "Agricultural Extension Internship",
            "org": "ministry-of-education",
            "category": "internships",
            "type": "INTERNSHIP",
            "location": "Burao",
            "country": "Somaliland",
            "remote": False,
            "days": 19,
            "views": 190,
            "featured": False,
            "skills": ["Agriculture", "Communication"],
            "tags": ["Agriculture", "Field"],
            "levels": bachelor,
            "short": "A field internship supporting agricultural training sessions near Burao.",
            "description": "Interns help facilitators run practical sessions with students and cooperatives. The work is outdoors and requires travel from Burao.\n\nThis is a strong fit for agriculture students, not a software placement.",
            "eligibility": "Students in agriculture, education, or rural development.",
            "requirements": "Willingness to travel and a faculty letter.",
            "benefits": "Stipend and field supervision.",
            "url": "https://moe.govsomaliland.org",
        },
        {
            "title": "Business Analyst Trainee",
            "org": "dahabshiil",
            "category": "jobs",
            "type": "JOB",
            "location": "Hargeisa",
            "country": "Somaliland",
            "remote": False,
            "days": 7,
            "views": 770,
            "featured": False,
            "skills": ["Excel", "Finance", "Communication"],
            "tags": ["Finance", "Analysis"],
            "levels": graduate,
            "short": "A trainee analyst role supporting weekly performance reports.",
            "description": "The trainee prepares clear tables, checks figures, and writes a short weekly note for managers. Finance or business graduates are the main audience.\n\nSoftware engineering students with strong spreadsheet habits may still apply.",
            "eligibility": "Graduates who can work full time in Hargeisa.",
            "requirements": "Spreadsheet test during the interview.",
            "benefits": "Salary and internal training.",
            "url": "https://www.dahabshiil.com",
        },
        {
            "title": "Engineering Design Challenge",
            "org": "gollis-university",
            "category": "competitions",
            "type": "COMPETITION",
            "location": "Hargeisa",
            "country": "Somaliland",
            "remote": False,
            "days": 28,
            "views": 340,
            "featured": False,
            "skills": ["Engineering", "Design"],
            "tags": ["Engineering"],
            "levels": bachelor,
            "short": "Design a low-cost campus water point and present the prototype.",
            "description": "Teams submit drawings and a materials list, then present to engineering faculty. The challenge rewards buildable ideas over polished slides.\n\nSoftware students can join as the data or documentation partner.",
            "eligibility": "University teams of up to four.",
            "requirements": "Concept note.",
            "benefits": "Materials budget for finalists.",
            "url": "https://gollisuniversity.org",
        },
        {
            "title": "Community Health Research Assistant",
            "org": "amoud-university",
            "category": "jobs",
            "type": "JOB",
            "location": "Borama",
            "country": "Somaliland",
            "remote": False,
            "days": 13,
            "views": 40,
            "featured": False,
            "status": "PENDING",
            "skills": ["Research", "Medicine"],
            "tags": ["Health"],
            "levels": ["Bachelor"],
            "short": "Awaiting review: a research assistant post for a community health study.",
            "description": "This listing is pending admin approval and should not appear in the public catalogue until it is approved.",
            "eligibility": "Health graduates in Borama.",
            "requirements": "CV and a writing sample.",
            "benefits": "Short contract.",
            "url": "https://amouduniversity.org",
        },
        {
            "title": "Summer Design Residency",
            "org": "hargeisa-tech-hub",
            "category": "fellowships",
            "type": "FELLOWSHIP",
            "location": "Hargeisa",
            "country": "Somaliland",
            "remote": False,
            "days": 45,
            "views": 15,
            "featured": False,
            "status": "DRAFT",
            "skills": ["Design"],
            "tags": ["Design"],
            "levels": any_level,
            "short": "Draft residency listing that is not published yet.",
            "description": "Internal draft for a summer design residency. Admins can edit and approve it when the dates are confirmed.",
            "eligibility": "To be confirmed.",
            "requirements": "To be confirmed.",
            "benefits": "To be confirmed.",
            "url": "https://hargeisatechhub.example",
        },
        {
            "title": "Overseas Data Entry Offer",
            "org": "shaqodoon",
            "category": "jobs",
            "type": "JOB",
            "location": "International",
            "country": "International",
            "remote": True,
            "days": 10,
            "views": 80,
            "featured": False,
            "status": "REJECTED",
            "skills": ["Excel"],
            "tags": ["Unverified"],
            "levels": any_level,
            "short": "Rejected after review because the employer could not be verified.",
            "description": "This sample shows a rejected listing. It stays in the admin queue and is hidden from students.",
            "eligibility": "Not published.",
            "requirements": "Not published.",
            "benefits": "Not published.",
            "url": "https://shaqodoon.org",
        },
    ]

    opp_map: dict[str, Opportunity] = {}
    for item in opportunities:
        slug = slugify(item["title"])
        row = Opportunity(
            title=item["title"],
            slug=slug,
            description=item["description"],
            short_description=item["short"],
            organization_id=org_map[item["org"]].id,
            category_id=category_map[item["category"]].id,
            opportunity_type=item["type"],
            location=item["location"],
            country=item["country"],
            is_remote=item["remote"],
            eligibility=item["eligibility"],
            requirements=item["requirements"],
            benefits=item["benefits"],
            application_url=item["url"],
            deadline=_days(item["days"]),
            start_date=_days(item["days"] + 14),
            end_date=_days(item["days"] + 90),
            tags=item["tags"],
            skills=item["skills"],
            education_levels=item["levels"],
            featured=item["featured"],
            status=item.get("status", OpportunityStatus.APPROVED.value),
            views=item["views"],
        )
        db.add(row)
        opp_map[slug] = row

    admin = User(
        full_name="HOH Admin",
        username="hoh-admin",
        email="admin@hargeisaopportunityhub.so",
        password_hash=hash_password("Admin123!"),
        location="Hargeisa",
        role=Role.ADMIN.value,
        is_verified=True,
        onboarding_complete=True,
        bio="Platform administrator for Hargeisa Opportunity Hub.",
        skills=[],
        interests=[],
        preferred_categories=[],
        preferred_locations=["Hargeisa"],
    )
    student = User(
        full_name="Ayaan Hassan",
        username="ayaan-hassan",
        email="ayaan@uoh.edu.so",
        password_hash=hash_password("Student123!"),
        phone="+252 63 400 0000",
        location="Hargeisa",
        university="University of Hargeisa",
        faculty="Faculty of ICT",
        department="Software Engineering",
        graduation_year=2027,
        education_level="Bachelor",
        skills=["Python", "TypeScript", "React", "AI"],
        interests=["Software Engineering", "Artificial Intelligence"],
        preferred_categories=["INTERNSHIP", "SCHOLARSHIP", "HACKATHON", "JOB", "COURSE"],
        preferred_locations=["Hargeisa", "Remote", "Somaliland"],
        bio="Software engineering student looking for internships, AI scholarships, and hackathons.",
        role=Role.STUDENT.value,
        is_verified=True,
        onboarding_complete=True,
    )
    db.add(admin)
    db.add(student)
    db.flush()

    def opp(title: str) -> Opportunity:
        return opp_map[slugify(title)]

    for title in [
        "Telesom Software Engineering Internship",
        "AI for Somaliland Hackathon",
        "Undergraduate Scholarship in Artificial Intelligence",
        "Junior Frontend Developer",
        "University Coding Challenge",
    ]:
        db.add(Bookmark(user_id=student.id, opportunity_id=opp(title).id))

    tracking = [
        ("Undergraduate Scholarship in Artificial Intelligence", ApplicationStatus.SAVED.value, "Collect transcript and faculty reference."),
        ("AI for Somaliland Hackathon", ApplicationStatus.PLANNED.value, "Ask Hodan to join the team."),
        ("Telesom Software Engineering Internship", ApplicationStatus.APPLIED.value, "Submitted the portfolio link."),
        ("Dahabshiil Graduate Finance Internship", ApplicationStatus.INTERVIEW.value, "Interview on Thursday. Review spreadsheet basics."),
        ("Remote AI Product Course", ApplicationStatus.ACCEPTED.value, "Seat confirmed. Block five hours a week."),
        ("National Student Debate", ApplicationStatus.REJECTED.value, "Team was not shortlisted."),
    ]
    for title, status, notes in tracking:
        applied_at = _days(-2) if status in {ApplicationStatus.APPLIED.value, ApplicationStatus.INTERVIEW.value, ApplicationStatus.ACCEPTED.value, ApplicationStatus.REJECTED.value} else None
        db.add(
            Application(
                user_id=student.id,
                opportunity_id=opp(title).id,
                status=status,
                notes=notes,
                applied_at=applied_at,
            )
        )

    db.add_all(
        [
            Notification(
                user_id=student.id,
                title="Welcome to HOH",
                message="Your feed is tuned for software engineering, artificial intelligence, Hargeisa, and remote work.",
                type=NotificationType.SYSTEM.value,
                link="/dashboard",
            ),
            Notification(
                user_id=student.id,
                title="A new match for you",
                message="The AI for Somaliland Hackathon lines up with artificial intelligence and software engineering.",
                type=NotificationType.RECOMMENDATION.value,
                link="/opportunities/ai-for-somaliland-hackathon",
            ),
        ]
    )
    db.add_all(
        [
            Setting(key="site_name", value="HOH — Hargeisa Opportunity Hub"),
            Setting(key="support_email", value="hello@hargeisaopportunityhub.so"),
            Setting(key="announcement", value=""),
        ]
    )
    db.commit()
